exclude: "(frontend/src/generated/|backend/alembic/versions/)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Backend hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        entry: ruff check . --fix
        files: backend/
      - id: ruff-format
        entry: ruff format .
        files: backend/

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.0"
    hooks:
      - id: prettier
        files: frontend/
        types_or: [javascript, jsx, ts, tsx]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.20.0"
    hooks:
      - id: eslint
        files: frontend/
        types_or: [javascript, jsx, ts, tsx]
