exclude: "(frontend/src/generated/|backend/alembic/versions/)"
ci:
  autofix_prs: true
  skip: []
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Backend hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        entry: ruff check . --fix
        files: backend/
      - id: ruff-format
        entry: ruff format .
        files: backend/

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: frontend/
        types_or: [javascript, jsx, ts, tsx]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.2.0"
    hooks:
      - id: eslint
        additional_dependencies: ["eslint@7.20.0", "eslint-config-react-app@7.0.1", "eslint-plugin-cypress@2.15.1"]
        files: frontend/
        types_or: [javascript, jsx, ts, tsx]
