name: pre-commit

on:
  push:
    branches:
      - main
    paths:
      - '.pre-commit-config.yaml'
      - '**.py'
      - '**.js'
  pull_request:
    types: [opened, synchronize]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        cache-dependency-path: "frontend/yarn.lock"
        cache: 'yarn'
    - run: cd frontend && yarn install
    - uses: pre-commit/action@v3.0.1
