name: FE

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: 1
       COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: "scorecard2-frontend:latest"
          cache-from: type=gha,scope=ci-test
          cache-to: type=gha,mode=max,scope=ci-test
          context: frontend
          load: true

  test:
    needs: [build]
    runs-on: ubuntu-latest
    env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile
        yarn test --coverage
