name: BE

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: 1
       COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend
      id: docker_build_backend
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: "scorecard2-backend:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: backend
        load: true

  test:
    needs: [build]
    runs-on: ubuntu-latest
    env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start containers
      run: |
        mv env-template .env
        docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
        docker-compose exec -T postgres createdb -U postgres apptest

    - name: Model-migration check
      run: |
        docker-compose exec -T backend alembic upgrade head
        docker-compose exec -T backend alembic check

    - name: Run backend tests
      run: |
        docker-compose exec -T backend pytest -v -s --cov=app --cov-report term-missing

    - name: Log docker status
      if: ${{ always() }}
      run: |
        docker-compose ps
        docker-compose logs -t
